name: Manage Autopilot

on:
  schedule:
    # Run at 8:00 AM and 6:00 PM UTC every day
    - cron: '0 8,18 * * *'
  workflow_dispatch: # Allows you to run manually if needed

jobs:
  run_manage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run Manage Core
        run: python core/manager.py
